DQN:
  # Tuned
  CartPole-v0:
    agent_class: dqn
    reward_scale: 1
    gamma: 0.97
    target_step: 1000
    net_dim: 128
    num_layer: 3
    batch_size: 128
    repeat_times: 1
    explore_rate: 0.25
    eval_gap: 32
    eval_times: 8
    break_step: !!float 8e4
    learner_gpus: 0
  # Tuned
  LunarLander-v2:
    agent_class: dqn
    reward_scale: 1
    gamma: 0.99
    target_step: 1000
    net_dim: 128
    num_layer: 3
    batch_size: 64
    repeat_times: 1
    explore_noise: 0.125
    eval_gap: 128
    eval_times: 32
    break_step: !!float 4e5
    learner_gpus: 0


DDPG: 
  # Tuned
  Pendulum:
    agent_class: ddpg
    reward_scale: 0.5  
    gamma: 0.97
    target_step: 1000
    net_dim: 128
    batch_size: 128
    repeat_times: 1
    explore_noise: 0.1
    eval_gap: 64
    eval_times: 8
    break_step: !!float 1e5
    learner_gpus: 0

  # Tuned
  LunarLanderContinuous-v2:
    agent_class: ddpg
    reward_scale: 1
    gamma: 0.99
    target_step: 1000
    net_dim: 128
    batch_size: 128
    repeat_times: 1
    explore_noise: 0.1
    eval_gap: 128
    eval_times: 16
    break_step: !!float 4e5
    learner_gpus: 0


  # Tuned
  BipedalWalker-v3:
    agent_class: ddpg
    reward_scale: 0.5
    gamma: 0.99
    target_step: 1000
    net_dim: 256
    num_layer: 3
    batch_size: 128
    repeat_times: 1
    explore_noise: 0.1
    eval_gap: 128
    eval_times: 8
    break_step: !!float 1e6
    learner_gpus: 0

PPO:
  Pendulum: